USE [master]
GO
/****** Object:  Database [educacao]    Script Date: 09/06/2021 22:26:09 ******/
CREATE DATABASE [educacao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'educacao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\educacao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'educacao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\educacao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [educacao] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [educacao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [educacao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [educacao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [educacao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [educacao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [educacao] SET ARITHABORT OFF 
GO
ALTER DATABASE [educacao] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [educacao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [educacao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [educacao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [educacao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [educacao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [educacao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [educacao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [educacao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [educacao] SET  DISABLE_BROKER 
GO
ALTER DATABASE [educacao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [educacao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [educacao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [educacao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [educacao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [educacao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [educacao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [educacao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [educacao] SET  MULTI_USER 
GO
ALTER DATABASE [educacao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [educacao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [educacao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [educacao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [educacao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [educacao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [educacao] SET QUERY_STORE = OFF
GO
USE [educacao]
GO
/****** Object:  User [leo]    Script Date: 09/06/2021 22:26:09 ******/
CREATE USER [leo] FOR LOGIN [leo] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[ps_inscrito]    Script Date: 09/06/2021 22:26:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ps_inscrito](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome_completo] [varchar](255) NULL,
	[genero] [tinyint] NULL,
	[cpf] [varchar](11) NULL,
	[telefone] [varchar](50) NULL,
	[data_nascimento] [date] NULL,
	[email] [varchar](255) NULL,
	[id_cidade] [int] NULL,
	[id_escola] [int] NULL,
	[created_at] [datetime] NULL,
 CONSTRAINT [PK_PS_INSCRITO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ps_inscrito] ADD  CONSTRAINT [DF_PS_INSCRITO_created_at]  DEFAULT (getdate()) FOR [created_at]
GO
USE [master]
GO
ALTER DATABASE [educacao] SET  READ_WRITE 
GO
